version: 2

sources:
  - name: heap
    database: proddb
    schema: heap_connect
    tables:
      - name: user_migrations
        description: This table keeps track of every identity call made to heap and logs the user id change and time
        freshness:
          warn_after:
            count: 1
            period: day
        columns:
          - name: from_user_id 
            identifier: heap_legacy_cookie_id
            description: The anonymous heap generated cookie id set at the time of the identify call
            tests:
              - not_null
          - name: to_user_id 
            identifier: heap_identity_user_id
            description: A hashed version of the user identity that all anonymous ids will be converted to upon identification
            tests:
              - not_null
              - unique
          - name: time 
            identifier: heap_identified_at 
            description: The timestamp when the identify call was made

      - name: users
        description: This table includes a unique row for each Heap User ID. Heap will automatically merge these users when they have the same identity value. This means that multiple rows in this table could refer to the same user. 
        freshness:
          warn_after:
            count: 1
            period: day
        columns:
          - name: user_id 
            identifier: heap_user_id
            description: Unique ID of user, randomly generated by Heap.
            tests:
              - not_null
              - unique
          - name: joindate
            identifier: heap_user_first_session_time
            description: The timestamp that this user was first detected by Heap
          - name: last_modified
            identifier: heap_user_last_updated
            description: The last time this user was merged with another user as a result of both users being identified with the same identity value 
          - name: identity
            identifier: drf_user_id
            description: The DRF unique user id that is passed to Heap in order to merge users across different device and browser combinations 
          - name: email
            identifier: drf_user_email
            description: The email of the user 
          - name: bets_id
            identifier: drf_bets_id
            description: Not sure 
          - name: signup_type
            identifier: drf_signup_type
            description: Not sure 
            
      - name: sessions
        description: On web, a session ends after 30 minutes of pageview inactivity from the user. On mobile, a session ends after 5 minutes of inactivity, regardless of whether the app’s background or foreground state.
        freshness:
          warn_after:
            count: 1
            period: day
        columns: 
         - name: session_id
           identifier: heap_session_id
           description: ID of associated session, randomly generated by Heap
           tests:
             - not_null
             - unique
         - name: user_id
           identifier: heap_user_id
           description: ID of associated user, randomly generated by Heap
         - name: time
           identifier: heap_session_start_time
           description: Timestamp without timezone of when session started 
         - name: library
           identifier: heap_session_source
           description: Version of Heap library which initiated the session
         - name: platform 
           identifier: heap_user_platform
           description: users operating system
         - name: device_type
           identifier: heap_user_device_type
           description: Mobile, Tablet, or Desktop
         - name: country
           identifier: heap_session_country 
           description: country associated with the ip address of the session 
         - name: region
           identifier: heap_session_region
           description: region or state associated with the ip address of the session 
         - name: city
           identifier: heap_session_city
           description: city associated with the ip address of the session 
         - name: ip
           identifier: heap_session_ip
           description: the ip address associated with the users session 
         - name: referrer
           identifier: heap_session_referrer
           description: URL that linked to your site and initiated the session. If the user navigated directly to your site, or referral headers were stripped, then this value will appear as NULL
         - name: landing_page 
           identifier: heap_session_landing_page
           description: URL of the first pageview of the session 
         - name: landing_page_query
           identifier: heap_session_landing_page_query
           description: The query parameters of the first page of the user’s session
         - name: landing_page_hash 
           identifier: heap_session_landing_page_hash
           description: The hash route of the first page of the user’s session
         - name: browser 
           identifier: heap_session_browser
           description: users browser used during the session 
         - name: utm_source 
           identifier: heap_session_utm_source
           description: value of the utm_source query parameter
         - name: utm_campaign 
           identifier: heap_session_utm_campaign
           description: value of the utm_campaign query parameter
         - name: utm_medium 
           identifier: heap_session_utm_medium
           description: value of the utm_medium query parameter
         - name: utm_term
           identifier: heap_session_utm_term
           description: value of the utm_term query parameter
         - name: utm_content 
           identifier: heap_session_utm_content
           description: value of the utm_content query parameter
         - name: device
           identifier: heap_session_device
           description: users device model
         - name: carrier
           identifier: heap_session_carrier
           description: users mobile carrier 
         - name: app_name
           identifier: heap_session_app_name
           description: current name of mobile app
         - name: app_version 
           identifier: heap_session_app_version
           description: current version number of mobile app
      
      - name: pageviews
        description: Heap will create a table that contains every pageview by default
        freshness:
          warn_after:
            count: 1
            period: day
        columns: 
         - name: event_id
           identifier: heap_pageview_id
           description: Unique ID of associated pageview event
           tests:
            - not_null
            - unique
         - name: user_id
           identifier: heap_user_id
           description: Unique ID of associated user, randomly generated by Heap
         - name: session_id
           identifier: heap_session_id
           description: Unique ID of associated session, randomly generated by Heap
         - name: time 
           identifier: heap_pageview_time
           description: Timestamp without timezone of when the pageview occurred
         - name: library 
           identifier: heap_pageview_source
           description: Version of Heap library which initiated the session 
         - name: platform 
           identifier: heap_session_platform
           description: Users operating system 
         - name: device_type 
           identifier: heap_session_device_type 
           description: Mobile, Tablet, or Desktop
         - name: country
           identifier: heap_session_country
           description: Country in which user session occurred, based on IP
         - name: region 
           identifier: heap_session_region
           description: Region or State in which user session occurred, based on IP
         - name: city 
           identifier: heap_session_city
           description: City in which user session occurred, based on IP
         - name: ip
           identifier: heap_session_ip
           description: The IP address for the session, which is used for determining geolocation
         - name: referrer 
           identifier: heap_session_referrer
           description: URL that linked to your site and initiated the session.If the user navigated directly to your site, or referral headers were stripped, then this value will appear as NULL downstream
         - name: landing_page 
           identifier: heap_session_landing_page
           description: URL of the first pageview of the session
         - name: landing_page_query 
           identifier: heap_session_landing_page_query
           description: The query parameters of the first page of the user’s session
         - name: landing_page_hash
           identifier: heap_session_landing_page_hash
           description: The hash route of the first page of the user’s session
         - name: browser 
           identifier: heap_session_browser
           description: The users browser during the session 
         - name: browser 
           identifier: heap_session_browser
           description: users browser used during the session 
         - name: utm_source 
           identifier: heap_session_utm_source
           description: value of the utm_source query parameter
         - name: utm_campaign 
           identifier: heap_session_utm_campaign
           description: value of the utm_campaign query parameter
         - name: utm_medium 
           identifier: heap_session_utm_medium
           description: value of the utm_medium query parameter
         - name: utm_term
           identifier: heap_session_utm_term
           description: value of the utm_term query parameter
         - name: utm_content 
           identifier: heap_session_utm_content
           description: value of the utm_content query parameter
         - name: device
           identifier: heap_session_device
           description: users device model
         - name: carrier
           identifier: heap_session_carrier
           description: users mobile carrier 
         - name: app_name
           identifier: heap_session_app_name
           description: current name of mobile app
         - name: app_version 
           identifier: heap_session_app_version
           description: current version number of mobile app
         - name: view_controller 
           identifier: heap_pageview_view_controller
           description: name of the current view controller
         - name: screen_a11y_id
           identifier: heap_pageview_screen_a11y_id
           description: accessibilityIdentifier for the current view controller
         - name: screen_a11y_label
           identifier: heap_pageview_screen_a11y_label
           description: accessibilityLabel for the current view controller

      - name: all_events
        description: Heap will create a table called all_events, which contains all defined or custom API events, pageviews, and sessions you have synced, as well as the built-in pageview event. 
        freshness:
          warn_after:
            count: 1
            period: day
        columns: 
         - name: event_id 
           identifier: heap_event_id
           description: Unique ID of associated event, randomly generated by Heap
         - name: user_id
           identifier: heap_user_id
           description: Unique ID of associated user, randomly generated by Heap
         - name: session_id
           identifier: heap_session_id
           description: Unique ID of associated session, randomly generated by Heap 
         - name: time
           identifier: heap_event_time
           description: Timestamp without timezone of when event happened
         - name: event_table_name
           identifier: heap_event_name
           description: Name of the table where similar events can be found
